---
  eventstream_type:
    description: "Either StateChange or CheckResult"
    type: "string"
    required: true
  api_url:
    description: "Base Icinga2 URL"
    type: "array"
    required: true
  api_user:
    description: "Icinga2 API User"
    type: "string"
    required: true
  api_password:
    description: "Icinga2 API Password"
    type: "string"
    required: true
  api_queue:
    description: "Custom queue name for Icinga2 API access"
    type: "string"
    required: true
    default: "icinga2req"
  cert_file:
    description: "Path to (CA) Certificate file for Icinga2 API Access"
    type: "string"
    required: false
  filter:
    description: "Filter out unwanted events"
    type: "object"
    required: false
